{"zhuyejiekou": [
{"name":"默认主页","url":"http://123.250idc.com/mogai_api.php/v1.vod"},
{"name":"极酷视频","url":"https://jiku.vip/mogai_api.php/v1.vod"},    
{"name":"飓风影院(推荐)","url": "http://yidayy.top/lehailb_api.php/v1.vod"},
{"name":"飓风影视2","url": "http://jf.35ys.cc/lehailb_api.php/v1.vod"},
{"name":"青豆","url":"http://150.158.133.36:9904/qingdoujiekou.php/v1.vod"},
{"name":"暖光影视","url":"https://app.bl210.com/api.php/v1.vod"},
{"name":"痞痞狸","url":"http://app.ppli.xyz/api.php/v1.vod"},
{"name":"影视猫","url":"https://vip.wscyun.com/api.php/v1.vod"},
{"name":"筋斗云影视","url":"https://tv.jindcloud.com/api.php/v1.vod"},
{"name":"4K影院(推荐)","url":"http://1api.4kdytv.com/api.php/v1.vod"},
{"name":"独播社(推荐)","url":"http://35ys.cc/api.php/v1.vod"},
{"name":"秒播365(推荐)","url":"https://www.kan365.xyz/api.php/app/"},
{"name":"寻常影视(推荐)","url":"http://tv.91ymz.cn/api.php/v1.vod"},
{"name":"琅琊影视","url": "http://fgyuu.top/lehailb_api.php/v1.vod"},
{"name":"爱西西(推荐)","url":"https://myaixixi.com/xgapp.php/v1/"},
{"name":"段友影视","url":"http://121.204.249.135:4433/ruifenglb_api.php/v1.vod"},
{"name":"星空影视(推荐)","url":"https://xkys.tv/xgapp.php/v1/"},
{"name":"虎猫视频","url":"https://humaosp.com/mogai_api.php/v1.vod"},
{"name":"DC 影视","url":"http://chaorenbb.com/api.php/v1.vod"},
{"name":"月儿影视","url":"https://yue52.xyz/api.php/v1.vod"},
{"name":"粉象视界","url":"http://42.157.129.15:34444/lvdou_api.php/v1.vod"},
{"name":"渔渔影视(推荐)","url":"http://luobo.yugenye.site/api.php/v1.vod"},
{"name":"CC影视","url":"https://ccbug.cc/lvdou_api.php/v1.vod"},
{"name":"Hi影视","url":"http://114.132.251.111:999/lvdou_api.php/v1.vod"},
{"name":"余生影视","url":"http://yu.cuicanys.cn/lvdou_api.php/v1.vod"},
{"name":"双鹿影院","url":"http://cr.slidc.top/mubai_api.php/m2.vod"},
{"name":"嗷呜视频","url":"http://www.cx99999.cn/lvdou_api.php/v1.vod"},
{"name":"懒猫电影","url":"http://www.esellauto.com/ruifenglb_api.php/v1.vod"},
{"name":"追剧吧","url":"http://zhuiju8.vip/api.php/v1.vod"},
{"name":"心爱影视(推荐)","url":"https://xays6677.com/mogai_api.php/v1.vod"},
{"name":"手指影视(推荐)","url":"https://szys5678.com/mogai_api.php/v1.vod"},
{"name":"HG影视(推荐)","url":"http://hgyx.vip/api.php/v1.vod"},
{"name":"天空影视","url":"https://www.tkys.tv/xgapp.php/v2/"},
{"name":"奈非迷","url":"https://app.netflixmi.com/api.php/v1.vod"},
{"name":"蓝光视频","url":"http://vip.91iqiyi.com/mogai_api.php/v1.vod"},
{"name":"快云影音(推荐)","url":"https://www.kuaiyunyy.com/api.php/app/"},
{"name":"三日影视","url":"https://www.3ri.net/api.php/v1.vod"},
{"name":"大熊","url":"https://www.555dy5.com/api.php/app/"},
{"name":"迪迪影视","url":"http://dd88.icu:6080/xgapp.php/v2/"},
{"name":"爱酷影视","url":"https://www.zhanlangbu.com/ruifenglb_api.php/v1.vod"},
{"name":"CJT影院","url":"https://www.cjt521.com/api.php/v1.vod"},
{"name":"白嫖影视","url":"http://zgjxdtg.cn/api.php/v1.vod"},
{"name":"零刻电影","url":"https://ys.ling00.cn/api.php/v1.vod"},
{"name":"F7高清","url":"http://bc.haokanju1.cc/lvdou_api.php/v1.vod"},
{"name":"阿里影视","url":"http://aliys.cn:90/api.php/v1.vod"},
{"name":"爱看美剧","url":"https://www.uumjw.com/api.php/v1.vod"},
{"name":"追剧达人","url":"https://www.zhuijudaren.com/mogai_api.php/v1.vod"},
{"name":"晗先森","url":"https://hantv.top/api.php/v1.vod"},
{"name":"全能","url": "https://qnys5566.com/mogai_api.php/v1.vod"},
{"name":"流星","url": "http://fkxs2233.com/mogai_api.php/v1.vod"},
{"name":"天天影视","url": "https://app.daishusc.com/api.php/v1.vod"},
{"name":"麻子视频","url": "http://www.lltpys.com/api.php/app/"},
{"name":"云海官方","url": "http://app1.udo.cc/api.php/app/"},
{"name":"全能看剧","url": "https://www.18mv.club/api.php/v1.vod"},
{"name":"美剧虫","url":"https://meijuchong.com/api.php/v1.vod"},
{"name":"天空影视","url":"https://www.tkys.tv/xgapp.php/v2/"},
{"name":"益达影院","url":"http://luobu.yss6080.com/mogai_api.php/v1.vod"},
{"name":"躺平影视","url":"http://www.lltpys.com/api.php/app/"},
{"name":"柚子视频","url":"http://yz.26ys.cn/api.php/v1.vod"},
{"name":"初心影视","url":"https://www.18mv.club/api.php/v1.vod"},
{"name":"月色影视","url":"http://69ty.cc/mogai_api.php/v1.vod"},
{"name":"蜜蜂影视","url":"http://app.f8tp.com/lvdou_api.php/v1.vod"},
{"name":"樱花动漫","url":"https://www.dmwu.cc/api.php/v1.vod"},
{"name":"小白动漫","url":"http://121.62.60.222:20222/mogai_api.php/v1.vod"},
{"name":"QC影视","url":"https://www.qcsvip.com/mogai_api.php/v1.vod"},
{"name":"U5影视","url":"https://appx.uy07.com/api.php/v1.vod"},
{"name":"爱影视","url":"https://www.hzlff.cn/api.php/v1.vod"},
{"name":"多啦咪PRO","url":"http://yuenos-pro.miyuen.cn/qingdoujiekou.php/v1.vod"},
{"name":"比邻影视","url":"http://0hzy.cn:9990/mogai_api.php/v1.vod"},
{"name":"豆渣影视","url":"http://douzhayss.cc/api.php/v1.vod"},
{"name":"黄河影视","url":"http://i.ledu8.cn/api.php/v1.vod"},
{"name":"晗先森","url":"https://hantv.top/api.php/v1.vod"},
{"name":"极酷视频","url":"https://jiku.vip/mogai_api.php/v1.vod"},
{"name":"冷视TV","url":"https://len.tv/api.php/v1.vod"},
{"name":"橘子影视","url":"http://jz.juzidy.vip/mogai_api.php/v1.vod"},
{"name":"看剧吧","url":"http://app.ishen520.com/api.php/v1.vod"},
{"name":"绿豆视频","url":"https://v.lvdoui.cn/mogai_api.php/v1.vod"},
{"name":"蓝光视频","url":"http://vip.91iqiyi.com/mogai_api.php/v1.vod"},
{"name":"皮皮动漫","url":"http://dm.muying.me/mogai_api.php/v1.vod"},
{"name":"天天视频","url":"http://app.qianju.cc/api.php/v1.vod"},
{"name":"小蜻蜓","url":"http://3ketv.com/mogai_api.php/v1.vod"},
{"name":"猪猪影院","url":"http://app.2zdyy.com/api.php/v1.vod"},
{"name":"913e影视","url":"http://www.913e.net/xgapp.php/v1/"},
{"name":"播放呀","url":"https://www.bofangya.com/xgapp.php/v1/"},
{"name":"海胆影视","url":"http://xf123.cc/api.php/app/"},
{"name":"抹茶猪","url":"https://www.mczdyw.com/api.php/app/"},
{"name":"萌蛋蛋","url":"http://app.mengdandan.com/xgapp.php/v1/"}],
"caijizhan": [
{"name":"77","url":"http://api.kunyu77.com/api.php"},
{"name":"每天看看","url":"http://47.113.126.237:1234/api.php"},
{"name":"奇趣影院","url":"http://www.qiqu.me/api.php"},
{"name":"293","url":"http://293x.yhzy.xyz/mv/api.php"},
{"name":"M3U8.TV资源","url":"http://www.zycaiji.net:7788/api.php"},
{"name":"wabc(腾讯直采)","url":"https://wabc.ml/mao/1.php"},
{"name":"嘛哩嘛哩","url":"https://malimali3.com/api.php"},
{"name":"77电影","url":"https://www.77diany.com/api.php"},
{"name":"饭团影视","url":"http://television.wkfile.com/api.php"},
{"name":"饭后电影","url":"http://yinliub.cn/api.php"},
{"name":"极速官采","url":"http://gc.zhuijuba.vip/api.php"},
{"name":"看猫","url":"http://124.222.83.15:88/api.php"},
{"name":"酷猫影视","url":"https://www.pgcms10.com/api.php"},
{"name":"江北资源","url":"https://gfzycj.hnmj.vip/api.php"},
{"name":"一拳动漫","url":"http://47.97.68.224/api.php"},
{"name":"人人资源","url":"http://www.rrzyw.cc/api.php"},
{"name":"光速资源","url":"https://api.guangsuapi.com/api.php"},
{"name":"兔子窝","url":"http://cj.huimaojia.com:12345/api.php"},
{"name":"初恋云影视","url":"https://video.xuanqi.pro/api.php"},
{"name":"千寻时光","url":"http://wy.dqyhg.cn/api.php"},
{"name":"天堂资源","url":"http://vipmv.cc/api.php"},
{"name":"小猫咪","url":"http://zy.xiaomaomi.cc/api.php"},
{"name":"忆梦","url":"http://anltv.cn/api.php"},
{"name":"想看资源","url":"https://m3u8.xiangkanapi.com/api.php"},
{"name":"新浪资源","url":"http://api.xinlangapi.com/xinlangapi.php"},
{"name":"旋风云","url":"http://appimg.ssxmall.cn/api.php"},
{"name":"无尽资源","url":"https://api.wujinapi.com/api.php"},
{"name":"无尽资源2","url":"https://wujinzy.com/api.php"},
{"name":"晓成云","url":"http://cj.cygc.xyz/api.php"},
{"name":"松鼠资源","url":"https://m3u8.songshuzy.com/api.php"},
{"name":"极速蓝光","url":"http://hs.zhuijuba.vip/api.php"},
{"name":"樱花","url":"https://m3u8.apiyhzy.com/api.php"},
{"name":"樱花2","url":"https://yhzy.cc/api.php"},
{"name":"橘子影视","url":"http://jz.juzidy.vip/api.php"},
{"name":"橘猫影视","url":"http://www.zitv.cc/api.php"},
{"name":"段友影视","url":"http://shangjihuoke.com/api.php"},
{"name":"海外电影","url":"https://www.200121.com/api.php"},
{"name":"淘剧鸭","url":"https://so2.cc/api.php"},
{"name":"百度云","url":"https://api.apibdzy.com/api.php"},
{"name":"红牛资源","url":"https://www.hongniuzy2.com/api.php"},
{"name":"考拉TV","url":"https://ikaola.tv/api.php"},
{"name":"胖猫影视","url":"http://www.pangmaotv.com/api.php"},
{"name":"艾思影院","url":"https://www.aitee.cc/api.php"},
{"name":"荔枝影视","url":"http://www.zjys.vip/api.php"},
{"name":"蓝光影视资源","url":"http://www.zzrhgg.com/api.php"},
{"name":"红牛资源","url":"https://www.hongniuzy2.com/api.php"},
{"name":"考拉TV","url":"https://ikaola.tv/api.php"},
{"name":"胖猫影视","url":"http://www.pangmaotv.com/api.php"},
{"name":"艾思影院","url":"https://www.aitee.cc/api.php"},
{"name":"荔枝影视","url":"http://www.zjys.vip/api.php"},
{"name":"超高清影视","url":"http://shdmv.com/api.php"},
{"name":"速播云","url":"http://gcku.suboyun.vip/api.php"},
{"name":"速更资源","url":"https://sugengzy.cn/api.php"},
{"name":"酷点资源","url":"https://kudianzy.com/api.php"},
{"name":"量子资源","url":"http://cj.lziapi.com/api.php"},
{"name":"闪电","url":"http://shandianzy.cc/api.php"},
{"name":"闪电资源","url":"http://sdzyapi.com/api.php"},
{"name":"飘花电影","url":"http://www.zzrhgg.com/api.php"},
{"name":"飘零影院","url":"https://p2100.net/api.php"},
{"name":"飞速资源","url":"https://www.feisuzy.com/api.php"},
{"name":"饭后电影","url":"http://yinliub.cn/api.php"},
{"name":"首涂官采","url":"http://zy.ishoutu.com/api.php"},
{"name":"鱼乐资源","url":"https://api.ylzy1.com/api.php"},
{"name":"测试","url":"http://107.150.5.146:39000/maccms10-main/api.php"},
{"name":"麒麟资源","url":"http://www.qilinzyz.com/api.php"},
{"name":"CK资源","url":"http://www.feifei67.com/api.php"},
{"name":"推荐采集1","url":"http://www.zycaiji.net:7788/api.php"},
{"name":"推荐采集2","url":"http://101.34.7.151:600/api.php"},
{"name":"片库资源","url":"https://pianku.wang/api.php"},
{"name":"聚多影视","url":"http://vip.ji-ding-he.site/api.php"},
{"name":"剧好看","url":"https://www.juhaokan.cc/api.php"},
{"name":"快播云","url":"http://www.kuaibozy.com/api.php"},
{"name":"蓝光影视","url":"http://www.zzrhgg.com/api.php"}],
"lunbo": [
{"name": "斗鱼","fanye": "aHR0cHM6Ly93d3cuZG91eXUuY29tL2dhcGkvcmtjL2RpcmVjdG9yeS9taXhMaXN0LzJfMjA4Lw==","qianzhui": "aHR0cDovL2VwZy4xMTIxMTQueHl6L2RvdXl1Lw=="},
{"name": "虎牙","fanye": "aHR0cHM6Ly93d3cuaHV5YS5jb20vY2FjaGUucGhwP209TGl2ZUxpc3QmZG89Z2V0TGl2ZUxpc3RCeVBhZ2UmZ2FtZUlkPTIxMzUmdGFnQWxsPTAmY2FsbGJhY2s9Z2V0TGl2ZUxpc3RKc29ucENhbGxiYWNrJnBhZ2U9","qianzhui": "aHR0cHM6Ly9lcGcuMTEyMTE0Lnh5ei9odXlhLw=="},
{"name": "哔哩哔哩","fanye": "aHR0cHM6Ly9hcGkubGl2ZS5iaWxpYmlsaS5jb20veGxpdmUvd2ViLWludGVyZmFjZS92MS9zZWNvbmQvZ2V0TGlzdD9wbGF0Zm9ybT13ZWImcGFyZW50X2FyZWFfaWQ9MTAmYXJlYV9pZD0zMyZzb3J0X3R5cGU9b25saW5lJnBhZ2U9","qianzhui": "aHR0cHM6Ly9lcGcuMTEyMTE0Lnh5ei9iaWxpLw=="},
{"name": "HY怀旧游戏","fanye": "aHR0cHM6Ly93d3cuaHV5YS5jb20vY2FjaGUucGhwP209TGl2ZUxpc3QmZG89Z2V0TGl2ZUxpc3RCeVBhZ2UmZ2FtZUlkPTEwMDEyNSZ0YWdBbGw9MCZjYWxsYmFjaz1nZXRMaXZlTGlzdEpzb25wQ2FsbGJhY2smcGFnZT0=","qianzhui": "aHR0cDovLzEyNC4yMjMuMjEyLjM4OjgzL2h1eWEv"},
{"name": "HY体育","fanye": "aHR0cHM6Ly93d3cuaHV5YS5jb20vY2FjaGUucGhwP209TGl2ZUxpc3QmZG89Z2V0TGl2ZUxpc3RCeVBhZ2UmZ2FtZUlkPTIzNTYmdGFnQWxsPTAmY2FsbGJhY2s9Z2V0TGl2ZUxpc3RKc29ucENhbGxiYWNrJnBhZ2U9","qianzhui": "aHR0cDovLzEyNC4yMjMuMjEyLjM4OjgzL2h1eWEv"},
{"name": "DY户外","fanye":"aHR0cHM6Ly93d3cuZG91eXUuY29tL2dhcGkvcmtjL2RpcmVjdG9yeS9taXhMaXN0LzJfMTI0Lw==","qianzhui":"aHR0cDovLzEyNC4yMjMuMjEyLjM4OjgzL2RvdXl1Lw=="},
{"name": "HY户外","fanye": "aHR0cHM6Ly93d3cuaHV5YS5jb20vY2FjaGUucGhwP209TGl2ZUxpc3QmZG89Z2V0TGl2ZUxpc3RCeVBhZ2UmZ2FtZUlkPTIxNjUmdGFnQWxsPTAmY2FsbGJhY2s9Z2V0TGl2ZUxpc3RKc29ucENhbGxiYWNrJnBhZ2U9","qianzhui": "aHR0cDovLzEyNC4yMjMuMjEyLjM4OjgzL2h1eWEv"}],
"zhujiexi": "https://v.2080kk.com/home/api?type=ys&uid=1308653&key=behnpstwxBCHJMQ029&url=#https://jhjx.kuanjv.com/newky/?url=#https://json.iku.cool/api/?key=3qTKEDXBaIaOiGjYwX&url=#http://api.vip123kan.vip/?url=#https://json.hfyrw.com/mao.go?url=#https://json.pangujiexi.com:12345/json.php?url=#https://json.5lp.net/json.php?url=#https://vip.aiaine.com/api/?key=8FN8gNAySnvJiMllxZ&url=#https://vip.aiaine.com/api/?key=fOWaGgFU45zlIjvbHI&url=#https://api.m3u8.tv:5678/home/api?type=ys&uid=1931000&key=gktuvyzABEORSYZ135&url=#https://api.m3u8.tv:5678/home/api?type=ys&uid=12185285&key=ijkluxAELMRUWXY279&url=",
"beiyongjiexi": "https://jx.parwix.com:4433/player/analysis.php?v=#https://nbjx.vip/?url=#https://jx.parwix.com:4433/player/?url=#https://jx.58g8.com/1/?url=#http://m2090.com/?url=#https://www.yemu.xyz/?url=#https://jx.blbo.cc:4433/?url=#http://47.100.138.210:92/?url=",
"dianshizhibo": "http://lb.yy111.cn/A/1654955234.txt",
"tiyuzhibo": "https://m.zhibo8.net",
"guolvdizhi": "player.css#url=#cnzz.com#51.la#poster#api.php#player",
"reci": "https://v.sogou.com",
"wuqu": "aHR0cDovL3d3dy5kanV1LmNvbQ==",
"Home": {
"dy": {
"class": "全部$&class=#喜剧$&class=喜剧#爱情$&class=爱情#动作$&class=动作#枪战$&class=枪战#犯罪$&class=犯罪#惊悚$&class=惊悚#恐怖$&class=恐怖#悬疑$&class=悬疑#动画$&class=动画#家庭$&class=家庭#奇幻$&class=奇幻#魔幻$&class=魔幻#科幻$&class=科幻#战争$&class=战争#青春$&class=青春#剧情$&class=剧情#西部$&class=西部#纪录$&class=记录#音乐$&class=音乐#歌舞$&class=歌舞#运动$&class=运动#历史$&class=历史#武侠$&class=武侠#冒险$&class=冒险#传记$&class=传记",
"area": "全部$&area=#内地$&area=内地#香港$&area=香港#美国$&area=美国#欧洲$&area=欧洲#韩国$&area=韩国#日本$&area=日本#泰国$&area=泰国#印度$&area=印度#其它$&area=其它",
"year": "全部$&lang=&year=#2022$&lang=&year=2022#2021$&lang=&year=2021#2020$&lang=&year=2020#2019$&lang=&year=2019#2018$&lang=&year=2018#2017$&lang=&year=2017#2016-2011$&lang=&year=2016#2010-2000$&lang=&year=2010#90年代$&lang=&year=90#80年代$&lang=&year=80#更早$&lang=&year=70"
},
"dsj": {
"class": "全部$&class=#古装$&class=古装#言情$&class=言情#武侠$&class=武侠#偶像$&class=偶像#家庭$&class=家庭#青春$&class=青春#都市$&class=都市#喜剧$&class=喜剧#战争$&class=战争#军旅$&class=军旅#谍战$&class=谍战#悬疑$&class=悬疑#罪案$&class=罪案#穿越$&class=穿越#宫廷$&class=宫廷#历史$&class=历史#神话$&class=神话#科幻$&class=科幻#年代$&class=年代#农村$&class=农村#商战$&class=商战#剧情$&class=剧情#奇幻$&class=奇幻",
"area": "全部$&area=#内地$&area=内地#香港$&area=香港#美国$&area=美国#英国$&area=英国#韩国$&area=韩国#日本$&area=日本#泰国$&area=泰国#台湾$&area=台湾#其它$&area=其它",
"year": "全部$&lang=&year=#2022$&lang=&year=2022#2021$&lang=&year=2021#2020$&lang=&year=2020#2019$&lang=&year=2019#2018$&lang=&year=2018#2017$&lang=&year=2017#2016-2011$&lang=&year=2016#2010-2000$&lang=&year=2010#90年代$&lang=&year=90#80年代$&lang=&year=80#更早$&lang=&year=70"
},
"zy": {
"class": "全部$&class=#表演$&class=表演#播报$&class=播报#访谈$&class=访谈#体验$&class=体验#养成$&class=养成#游戏$&class=游戏#亲子$&class=亲子#美食$&class=美食#情感$&class=情感#选秀$&class=选秀#益智$&class=益智#晚会$&class=晚会#音乐$&class=音乐#文化$&class=文化#喜剧$&class=喜剧#曲艺$&class=曲艺#职场$&class=职场#脱口秀$&class=脱口秀#真人秀$&class=真人秀#竞技$&class=竞技#体育$&class=体育#萌宠$&class=萌宠",
"area": "全部$&area=#内地$&area=内地#香港$&area=香港#美国$&area=美国#韩国$&area=韩国#日本$&area=日本#台湾$&area=台湾",
"year": "全部$&lang=&year=#2022$&lang=&year=2022#2021$&lang=&year=2021#2020$&lang=&year=2020#2019$&lang=&year=2019#2018$&lang=&year=2018#2017$&lang=&year=2017#2016-2011$&lang=&year=2016#2010-2000$&lang=&year=2010#90年代$&lang=&year=90#80年代$&lang=&year=80#更早$&lang=&year=70"
},
"dm": {
"class": "全部$&class=#搞笑$&class=搞笑#番剧$&class=番剧#国创$&class=国创#大电影$&class=大电影#热血$&class=热血#催泪$&class=催泪#治愈$&class=治愈#励志$&class=励志#机战$&class=机战#战斗$&class=战斗#恋爱$&class=恋爱#科幻$&class=科幻#奇幻$&class=奇幻#魔幻$&class=魔幻#推理$&class=推理#校园$&class=校园#日常$&class=日常#经典$&class=经典#历史$&class=历史#美食$&class=美食#职场$&class=职场#偶像$&class=偶像#泡面$&class=泡面#冒险$&class=冒险#竞技$&class=竞技#武侠$&class=武侠#玄幻$&class=玄幻",
"area": "全部$&area=#内地$&area=内地#日本$&area=日本#欧美$&area=欧美#其它$&area=其它",
"year": "全部$&lang=&year=#2022$&lang=&year=2022#2021$&lang=&year=2021#2020$&lang=&year=2020#2019$&lang=&year=2019#2018$&lang=&year=2018#2017$&lang=&year=2017#2016-2011$&lang=&year=2016#2010-2000$&lang=&year=2010#90年代$&lang=&year=90#80年代$&lang=&year=80#更早$&lang=&year=70"
}
},
"zidingyi": [
{"name": "乐猪资源",
"url": "http://www.lezhutv.com",
"tihuan": "cnzz.com",
"User": "空",
"fenlei": "电视剧$/type/2-#电影$/type/1-#综艺$/type/3-#动漫$/type/4-#韩剧$/type/14-#M剧$/type/15-",
"houzhui": ".html",
"shifouercijiequ": "0",
"jiequqian": "空",
"jiequhou": "空",
"jiequshuzuqian": "class=\"vbox\"",
"jiequshuzuhou": "</a>",
"tupianqian": "data-original=\"",
"tupianhou": "\"",
"biaotiqian": "title=\"",
"biaotihou": "\"",
"lianjieqian": "href=\"",
"lianjiehou": "\"",
"sousuoqian": "/search-pg-1-wd-",
"sousuohou": ".html",
"sousuohouzhui": "/detail/",
"ssmoshi": "1",
"sousuoshifouercijiequ": "0",
"jspic": "空",
"jsname": "空",
"jsid": "空",
"ssjiequqian": "空",
"ssjiequhou": "空",
"ssjiequshuzuqian": "class=\"vbox\"",
"ssjiequshuzuhou": "</a>",
"sstupianqian": "data-original=\"",
"sstupianhou": "\"",
"ssbiaotiqian": "title=\"",
"ssbiaotihou": "\"",
"sslianjieqian": "href=\"",
"sslianjiehou": "\"",
"bfshifouercijiequ": "0",
"bfjiequqian": "空",
"bfjiequhou": "空",
"bfjiequshuzuqian": "class=\"list_block show\"",
"bfjiequshuzuhou": "</ul>",
"zhuangtaiqian": "class=\"yac\">",
"zhuangtaihou": "</p>",
"daoyanqian": "导演：</span>",
"daoyanhou": "</p>",
"zhuyanqian": "主演：</span>",
"zhuyanhou": "</p>",
"juqingqian": "class=\"tbox_js\">",
"juqinghou": "</div>",
"bfyshifouercijiequ": "0",
"bfyjiequqian": "空",
"bfyjiequhou": "空",
"bfyjiequshuzuqian": "<li>",
"bfyjiequshuzuhou": "</li>",
"bfbiaotiqian": "\">",
"bfbiaotihou": "</a>",
"bflianjieqian": "href=\"",
"bflianjiehou": "\""},
{"name": "厂长资源-蓝光",
"url": "https://qianoo.cn",
"tihuan": "aliyundrive",
"User": "空",
"fenlei": "电视剧$/dsj/page/#电影$/zuixindianying/page/#番剧$/fanju/page/#动漫$/dm/page/#国产剧$/gcj/page/#M剧$/meijutt/page/#韩剧$/hanjutv/page/",
"houzhui": "",
"shifouercijiequ": "0",
"jiequqian": "空",
"jiequhou": "空",
"jiequshuzuqian": "<li>",
"jiequshuzuhou": "</span>",
"tupianqian": "original=\"",
"tupianhou": "\"",
"biaotiqian": "alt=\"",
"biaotihou": "\"",
"lianjieqian": "qianoo.cn",
"lianjiehou": "\"",
"sousuoqian": "/xssearch?q=",
"sousuohou": "",
"sousuohouzhui": "/movie/",
"ssmoshi": "1",
"sousuoshifouercijiequ": "0",
"jspic": "pic",
"jsname": "name",
"jsid": "id",
"ssjiequqian": "空",
"ssjiequhou": "空",
"ssjiequshuzuqian": "<li>",
"ssjiequshuzuhou": "</span>",
"sstupianqian": "original=\"",
"sstupianhou": "\"",
"ssbiaotiqian": "alt=\"",
"ssbiaotihou": "\"",
"sslianjieqian": "qianoo.cn",
"sslianjiehou": "\"",
"bfshifouercijiequ": "0",
"bfjiequqian": "空",
"bfjiequhou": "空",
"bfjiequshuzuqian": "class=\"paly_list",
"bfjiequshuzuhou": "</div>",
"zhuangtaiqian": "上映：<span>",
"zhuangtaihou": "</span>",
"daoyanqian": "<li>导演：",
"daoyanhou": "</li>",
"zhuyanqian": "<li>主演：",
"zhuyanhou": "</li>",
"juqingqian": "class=\"yp_context\">",
"juqinghou": "</div>",
"bfyshifouercijiequ": "0",
"bfyjiequqian": "空",
"bfyjiequhou": "空",
"bfyjiequshuzuqian": "<a",
"bfyjiequshuzuhou": "/a>",
"bfbiaotiqian": ">",
"bfbiaotihou": "<",
"bflianjieqian": "qianoo.cn",
"bflianjiehou": "\""},
{"name": "555电影",
"url": "https://www.555dy.fun",
"tihuan": "cnzz.com",
"User": "User-Agent:Dart/2.14 (dart:io)",
"fenlei": "电视剧$/vodtype/2-#电影$/vodtype/1-#综艺纪录片$/vodtype/3-#动漫$/vodtype/4-#港台剧$/vodtype/15-#日韩剧$/vodtype/44-#欧M剧$/vodtype/45-",
"houzhui": ".html",
"shifouercijiequ": "1",
"jiequqian": "class=\"myui-vodlist clearfix",
"jiequhou": "</ul>",
"jiequshuzuqian": "class=\"myui-vodlist__thumb",
"jiequshuzuhou": "</span>",
"tupianqian": "original=\"",
"tupianhou": "\"",
"biaotiqian": "title=\"",
"biaotihou": "\"",
"lianjieqian": "href=\"",
"lianjiehou": "\"",
"sousuoqian": "/index.php/ajax/suggest?mid=1&wd=",
"sousuohou": "&limit=50",
"sousuohouzhui": "/voddetail/",
"ssmoshi": "0",
"sousuoshifouercijiequ": "0",
"jspic": "pic",
"jsname": "name",
"jsid": "id",
"ssjiequqian": "空",
"ssjiequhou": "空",
"ssjiequshuzuqian": "空",
"ssjiequshuzuhou": "空",
"sstupianqian": "空",
"sstupianhou": "空",
"ssbiaotiqian": "空",
"ssbiaotihou": "空",
"sslianjieqian": "空",
"sslianjiehou": "空",
"bfshifouercijiequ": "0",
"bfjiequqian": "空",
"bfjiequhou": "空",
"bfjiequshuzuqian": "class=\"myui-content__list",
"bfjiequshuzuhou": "</ul>",
"zhuangtaiqian": "更新：</span>",
"zhuangtaihou": "</p>",
"daoyanqian": "导演：</span>",
"daoyanhou": "</p>",
"zhuyanqian": "主演：</span>",
"zhuyanhou": "</p>",
"juqingqian": "class=\"data\" style=\"display: none;\">",
"juqinghou": "</span>",
"bfyshifouercijiequ": "0",
"bfyjiequqian": "空",
"bfyjiequhou": "空",
"bfyjiequshuzuqian": "<a",
"bfyjiequshuzuhou": "/a>",
"bfbiaotiqian": ">",
"bfbiaotihou": "<",
"bflianjieqian": "href=\"",
"bflianjiehou": "\""},	
{"name": "LIBVIO",
"url": "https://www.libvio.com",
"tihuan": "dd520.cc",
"User": "空",
"fenlei": "电视剧$/show/2--------#电影$/show/1--------#综艺$/show/3--------#动漫$/show/4--------#动作片$/show/1---动作-----#喜剧片$/show/1---喜剧-----#爱情片$/show/1---爱情-----#科幻片$/show/1---科幻-----#奇幻片$/show/1---奇幻-----#恐怖片$/show/1---恐怖-----#剧情片$/show/1---剧情-----#战争片$/show/1---战争-----#冒险片$/show/1---冒险-----#国产剧$/show/2-中国大陆-------#台剧$/show/2-中国台湾-------#港剧$/show/2-中国香港-------#韩剧$/show/2-韩国-------#日剧$/show/2-日本-------#M剧$/show/2-M国-------#英剧$/show/2-英国-------",
"houzhui": "---.html",
"shifouercijiequ": "0",
"jiequqian": "空",
"jiequhou": "空",
"jiequshuzuqian": "data",
"jiequshuzuhou": "</h4>",
"tupianqian": "original=\"",
"tupianhou": "\"",
"biaotiqian": "title=\"",
"biaotihou": "\"",
"lianjieqian": "href=\"",
"lianjiehou": "\"",
"sousuoqian": "/index.php/ajax/suggest?mid=1&wd=",
"sousuohou": "&limit=500",
"sousuohouzhui": "/detail/",
"ssmoshi": "0",
"sousuoshifouercijiequ": "0",
"jspic": "pic",
"jsname": "name",
"jsid": "id",
"ssjiequqian": "空",
"ssjiequhou": "空",
"ssjiequshuzuqian": "空",
"ssjiequshuzuhou": "空",
"sstupianqian": "空",
"sstupianhou": "空",
"ssbiaotiqian": "空",
"ssbiaotihou": "空",
"sslianjieqian": "空",
"sslianjiehou": "空",
"bfshifouercijiequ": "0",
"bfjiequqian": "空",
"bfjiequhou": "空",
"bfjiequshuzuqian": "class=\"stui-content__playlist",
"bfjiequshuzuhou": "</ul>",
"zhuangtaiqian": "class=\"data\">总集数：",
"zhuangtaihou": "</p>",
"daoyanqian": "class=\"data\">类型：",
"daoyanhou": "</p>",
"zhuyanqian": "class=\"data\">主演：",
"zhuyanhou": "</p>",
"juqingqian": "class=\"detail-content\"",
"juqinghou": "</span>",
"bfyshifouercijiequ": "0",
"bfyjiequqian": "空",
"bfyjiequhou": "空",
"bfyjiequshuzuqian": "<a",
"bfyjiequshuzuhou": "/a>",
"bfbiaotiqian": ">",
"bfbiaotihou": "<",
"bflianjieqian": "href=\"",
"bflianjiehou": "\""},
{"name": "周末电影",
"url": "https://www.zzzlike.vip",
"tihuan": "cnzz.com",
"User": "空",
"fenlei": "电视剧$/vodtype/2-#电影$/vodtype/1-#综艺$/vodtype/3-#动漫$/vodtype/4-",
"houzhui": ".html",
"shifouercijiequ": "0",
"jiequqian": "空",
"jiequhou": "空",
"jiequshuzuqian": "class=\"stui-vodlist__box",
"jiequshuzuhou": "</li>",
"tupianqian": "data-original=\"",
"tupianhou": "\"",
"biaotiqian": "title=\"",
"biaotihou": "\"",
"lianjieqian": "href=\"",
"lianjiehou": "\"",
"sousuoqian": "/vodsearch/-------------.html?wd=",
"sousuohou": "",
"sousuohouzhui": "/voddetail/",
"ssmoshi": "1",
"sousuoshifouercijiequ": "0",
"jspic": "空",
"jsname": "空",
"jsid": "空",
"ssjiequqian": "空",
"ssjiequhou": "空",
"ssjiequshuzuqian": "class=\"thumb",
"ssjiequshuzuhou": "</li>",
"sstupianqian": "data-original=\"",
"sstupianhou": "\"",
"ssbiaotiqian": "title=\"",
"ssbiaotihou": "\"",
"sslianjieqian": "href=\"",
"sslianjiehou": "\"",
"bfshifouercijiequ": "0",
"bfjiequqian": "空",
"bfjiequhou": "空",
"bfjiequshuzuqian": "class=\"stui-content__playlist clearfix",
"bfjiequshuzuhou": "</ul>",
"zhuangtaiqian": "class=\"pic-text text-right\">",
"zhuangtaihou": "</span>",
"daoyanqian": "导演：",
"daoyanhou": "</p>",
"zhuyanqian": "主演：",
"zhuyanhou": "</p>",
"juqingqian": "style=\"display: none;\">",
"juqinghou": "</span>",
"bfyshifouercijiequ": "0",
"bfyjiequqian": "空",
"bfyjiequhou": "空",
"bfyjiequshuzuqian": "<li",
"bfyjiequshuzuhou": "</li>",
"bfbiaotiqian": "\">",
"bfbiaotihou": "</a>",
"bflianjieqian": "href=\"",
"bflianjiehou": "\""},
{"name": "花猫TV",
"url": "http://www.huamaotv.com",
"tihuan": "cnzz.com",
"User": "空",
"fenlei": "电影$/type/1-#连续剧$/type/2-#综艺$/type/3-#动漫$/type/4-#",
"houzhui": ".html",
"shifouercijiequ": "0",
"jiequqian": "空",
"jiequhou": "空",
"jiequshuzuqian":"class=\"stui-vodlist__item",
"jiequshuzuhou": "</a>",
"tupianqian": "data-original=\"",
"tupianhou": "\"",
"biaotiqian": "title=\"",
"biaotihou": "\"",
"lianjieqian": "href=\"",
"lianjiehou": "\"",
"sousuoqian": "/index.php/ajax/suggest?mid=1&wd=",
"sousuohou": "&limit=500",
"sousuohouzhui": "/detail/",
"ssmoshi": "0",
"sousuoshifouercijiequ": "0",
"jspic": "pic",
"jsname": "name",
"jsid": "id",
"ssjiequqian": "空",
"ssjiequhou": "空",
"ssjiequshuzuqian": "空",
"ssjiequshuzuhou": "空",
"sstupianqian": "空",
"sstupianhou": "空",
"ssbiaotiqian": "空",
"ssbiaotihou": "空",
"sslianjieqian": "空",
"sslianjiehou": "空",
"bfshifouercijiequ": "0",
"bfjiequqian": "空",
"bfjiequhou": "空",
"bfjiequshuzuqian": "class=\"stui-content__playlist clearfix\"",
"bfjiequshuzuhou": "</ul>",
"zhuangtaiqian": "class=\"data\"",
"zhuangtaihou": "</p>",
"daoyanqian": "导演：</span>",
"daoyanhou": "</p>",
"zhuyanqian": "主演：</span>",
"zhuyanhou": "</p>",
"juqingqian": "",
"juqinghou": "",
"bfyshifouercijiequ": "0",
"bfyjiequqian": "空",
"bfyjiequhou": "空",
"bfyjiequshuzuqian": "<li>",
"bfyjiequshuzuhou": "</li>",
"bfbiaotiqian": "\">",
"bfbiaotihou": "</a>",
"bflianjieqian": "href=\"",
"bflianjiehou": "\""},
{"name": "VIP1280",
"url": "http://www.vip1280.net",
"tihuan": "cnzz.com",
"User": "空",
"fenlei": "电影$/frim/index1/page/#电视剧$/frim/index2/page/#港台剧$/frim/index3/page/#动作片$/frim/index6/page/#爱情片$/frim/index7/page/#科幻片$/frim/index8/page/#恐怖片$/frim/index9/page/#战争片$/frim/index10/page/#喜剧片$/frim/index11/page/#记录片$/frim/index12/page/#剧情片$/frim/index20/page/#动画片$/frim/index21/page/#欧M剧$/frim/index4/page/#日韩剧$/frim/index5/page/#泰剧$/frim/index22/page/",
"houzhui": ".html",
"shifouercijiequ": "0",
"jiequqian": "空",
"jiequhou": "空",
"jiequshuzuqian": "class=\"col-md-6 col-sm-4 col-xs-3\"",
"jiequshuzuhou": "</li>",
"tupianqian": "data-original=\"",
"tupianhou": "\"",
"biaotiqian": "title=\"",
"biaotihou": "\"",
"lianjieqian": "href=\"",
"lianjiehou": "\"",
"sousuoqian": "/index.php/ajax/suggest?mid=1&wd=",
"sousuohou": "&limit=500",
"sousuohouzhui": "",
"ssmoshi": "0",
"sousuoshifouercijiequ": "0",
"jspic": "pic",
"jsname": "name",
"jsid": "id",
"ssjiequqian": "空",
"ssjiequhou": "空",
"ssjiequshuzuqian": "空",
"ssjiequshuzuhou": "空",
"sstupianqian": "空",
"sstupianhou": "空",
"ssbiaotiqian": "空",
"ssbiaotihou": "空",
"sslianjieqian": "空",
"sslianjiehou": "空",
"bfshifouercijiequ": "0",
"bfjiequqian": "空",
"bfjiequhou": "空",
"bfjiequshuzuqian": "class=\"stui-content__playlist clearfix\"",
"bfjiequshuzuhou": "</ul>",
"zhuangtaiqian": "class=\"pic-text text-right\">",
"zhuangtaihou": "",
"daoyanqian": "导演：</span>",
"daoyanhou": "</a>",
"zhuyanqian": "主演：</span>",
"zhuyanhou": "</a>",
"juqingqian": "class=\"detail-sketch\"",
"juqinghou": "</span>",
"bfyshifouercijiequ": "0",
"bfyjiequqian": "空",
"bfyjiequhou": "空",
"bfyjiequshuzuqian": "<li >",
"bfyjiequshuzuhou": "</li>",
"bfbiaotiqian": "\">",
"bfbiaotihou": "</a>",
"bflianjieqian": "href=\"",
"bflianjiehou": "\""},
{"name": "创艺",
"url": "https://www.30dian.cn",
"tihuan": "cnzz.com",
"User": "空",
"fenlei": "电影$/vodshow/1--------#连续剧$/vodshow/2--------#动漫$/vodshow/4--------#综艺$/vodshow/3--------#纪录片$/vodshow/30--------",
"houzhui": "---.html",
"shifouercijiequ": "0",
"jiequqian": "空",
"jiequhou": "空",
"jiequshuzuqian": "class=\"myui-vodlist__box\"",
"jiequshuzuhou": "</span>",
"tupianqian": "original=\"",
"tupianhou": "\"",
"biaotiqian": "title=\"",
"biaotihou": "\"",
"lianjieqian": "href=\"",
"lianjiehou": "\"",
"sousuoqian": "/index.php/ajax/suggest?mid=1&wd=",
"sousuohou": "&limit=500",
"sousuohouzhui": "/voddetail/",
"ssmoshi": "0",
"sousuoshifouercijiequ": "0",
"jspic": "pic",
"jsname": "name",
"jsid": "id",
"ssjiequqian": "空",
"ssjiequhou": "空",
"ssjiequshuzuqian": "空",
"ssjiequshuzuhou": "空",
"sstupianqian": "空",
"sstupianhou": "空",
"ssbiaotiqian": "空",
"ssbiaotihou": "空",
"sslianjieqian": "空",
"sslianjiehou": "空",
"bfshifouercijiequ": "0",
"bfjiequqian": "空",
"bfjiequhou": "空",
"bfjiequshuzuqian": "id=\"playlist",
"bfjiequshuzuhou": "</ul>",
"zhuangtaiqian": "class=\"pic-text text-right\">",
"zhuangtaihou": "</span>",
"daoyanqian": "导演：",
"daoyanhou": "</p>",
"zhuyanqian": "主演：",
"zhuyanhou": "</p>",
"juqingqian": "style=\"display: none;\">",
"juqinghou": "</p>",
"bfyshifouercijiequ": "0",
"bfyjiequqian": "空",
"bfyjiequhou": "空",
"bfyjiequshuzuqian": "<li",
"bfyjiequshuzuhou": "</li>",
"bfbiaotiqian": "\">",
"bfbiaotihou": "</a>",
"bflianjieqian": "href=\"",
"bflianjiehou": "\""},
{"name": "9亿资源",
"tihuan": "cnzz.com",
"url": "https://www.9eii.com",
"fenlei": "热播剧集$/vodshow/zuijinrebodianshiju/page/#热播电影$/vodshow/zuijinrebodianying/page/#综艺$/vodshow/zongyi/page/#动漫$/vodshow/dongman/page/#国语配音电影$/vodshow/gypy/page/#国语配音剧集$/vodshow/guoyupeiyinhanju/page/#国语配音动漫$/vodshow/guoyupeiyindongman/page/#国产剧$/vodshow/lianxuju/area/中国大陆/page/#港剧$/vodshow/lianxuju/area/香港/page/#韩剧$/vodshow/lianxuju/area/韩国/page/#M剧$/vodshow/lianxuju/area/M国/page/#泰剧$/vodshow/lianxuju/area/泰国/page/#日剧$/vodshow/lianxuju/area/日本/page/#英剧$/vodshow/lianxuju/area/英国/page/",
"houzhui": ".html",
"shifouercijiequ": "0",
"jiequqian": "空",
"jiequhou": "空",
"jiequshuzuqian": "class=\"myui-vodlist__box\"",
"jiequshuzuhou": "</span>",
"tupianqian": "original=\"",
"tupianhou": "\"",
"biaotiqian": "title=\"",
"biaotihou": "\"",
"lianjieqian": "href=\"",
"lianjiehou": "\"",
"sousuoqian": "/index.php/ajax/suggest?mid=1&wd=",
"sousuohou": "&limit=500",
"sousuohouzhui": "/voddetail/",
"ssmoshi": "0",
"sousuoshifouercijiequ": "0",
"jspic": "pic",
"jsname": "name",
"jsid": "id",
"ssjiequqian": "空",
"ssjiequhou": "空",
"ssjiequshuzuqian": "空",
"ssjiequshuzuhou": "空",
"sstupianqian": "空",
"sstupianhou": "空",
"ssbiaotiqian": "空",
"ssbiaotihou": "空",
"sslianjieqian": "空",
"sslianjiehou": "空",
"bfshifouercijiequ": "0",
"bfjiequqian": "空",
"bfjiequhou": "空",
"bfjiequshuzuqian": "id=\"playlist",
"bfjiequshuzuhou": "</ul>",
"zhuangtaiqian": "更新：</span>",
"zhuangtaihou": "</p >",
"daoyanqian": "导演：</span>",
"daoyanhou": "</p >",
"zhuyanqian": "主演：</span>",
"zhuyanhou": "</p >",
"juqingqian": "简介：</span>",
"juqinghou": "<a",
"bfyshifouercijiequ": "0",
"bfyjiequqian": "空",
"bfyjiequhou": "空",
"bfyjiequshuzuqian": "<a",
"bfyjiequshuzuhou": "/a>",
"bfbiaotiqian": ">",
"bfbiaotihou": "<",
"bflianjieqian": "href=\"",
"bflianjiehou": "\""},
{"name": "飘花播播",
"url": "https://www.piaohuabo.com/",
"fenlei": "电影$/vodtype/1-#电视剧$/vodtype/2-#国产剧$/vodtype/13-#港台剧$/vodtype/14-#日韩剧$/vodtype/15-#欧美剧$/vodtype/16-#海外剧$/vodtype/20-#综艺$/vodtype/3-#动漫$/vodtype/4-",
"houzhui": ".html",
"shifouercijiequ": "0",
"jiequqian": "空",
"jiequhou": "空",
"jiequshuzuqian": "class=\"stui-vodlist__box\"",
"jiequshuzuhou": "</div>",
"tupianqian": "style=\"",
"tupianhou": "\"",
"biaotiqian": "title=\"",
"biaotihou": "\"",
"lianjieqian": "href=\"",
"lianjiehou": "\"",
"sousuoqian": "/index.php/ajax/suggest?mid=1&wd=",
"sousuohou": "&limit=500",
"sousuohouzhui": "/voddetail/",
"ssmoshi": "0",
"sousuoshifouercijiequ": "0",
"jspic": "pic",
"jsname": "name",
"jsid": "id",
"ssjiequqian": "空",
"ssjiequhou": "空",
"ssjiequshuzuqian": "空",
"ssjiequshuzuhou": "空",
"sstupianqian": "空",
"sstupianhou": "空",
"ssbiaotiqian": "空",
"ssbiaotihou": "空",
"sslianjieqian": "空",
"sslianjiehou": "空",
"bfshifouercijiequ": "0",
"bfjiequqian": "空",
"bfjiequhou": "空",
"bfjiequshuzuqian": "class=\"stui-content__playlist clearfix\"",
"bfjiequshuzuhou": "</ul>",
"zhuangtaiqian": "class=\"pic-text text-right\">",
"zhuangtaihou": "</span>",
"daoyanqian": "导演：",
"daoyanhou": "</p>",
"zhuyanqian": "主演：",
"zhuyanhou": "</p>",
"juqingqian": "简介：</span>",
"juqinghou": "</div>",
"bfyshifouercijiequ": "0",
"bfyjiequqian": "空",
"bfyjiequhou": "空",
"bfyjiequshuzuqian": "<a",
"bfyjiequshuzuhou": "/a>",
"bfbiaotiqian": ">",
"bfbiaotihou": "<",
"bflianjieqian": "href=\"",
"bflianjiehou": "\""},
{"name": "影渣渣",
"url": "https://www.yingzhazha.com/",
"fenlei": "电影$/vodshow/1--------#电视剧$/vodshow/2--------#国产剧$/vodshow/13--------#港台剧$/vodshow/14--------#日韩剧$/vodshow/15--------#欧美剧$/vodshow/16--------#海外剧$/vodshow/23--------#泰剧$/vodshow/37--------#综艺$/vodshow/3--------#动漫$/vodshow/4--------#体育赛事$/vodshow/22--------#电视直播$/vodshow/28--------",
"houzhui": "---.html",
"shifouercijiequ": "0",
"jiequqian": "空",
"jiequhou": "空",
"jiequshuzuqian": "class=\"myui-vodlist__box\"",
"jiequshuzuhou": "</span>",
"tupianqian": "original=\"",
"tupianhou": "\"",
"biaotiqian": "title=\"",
"biaotihou": "\"",
"lianjieqian": "href=\"",
"lianjiehou": "\"",
"sousuoqian": "/index.php/ajax/suggest?mid=1&wd=",
"sousuohou": "&limit=500",
"sousuohouzhui": "/voddetail/",
"ssmoshi": "0",
"sousuoshifouercijiequ": "0",
"jspic": "pic",
"jsname": "name",
"jsid": "id",
"ssjiequqian": "空",
"ssjiequhou": "空",
"ssjiequshuzuqian": "空",
"ssjiequshuzuhou": "空",
"sstupianqian": "空",
"sstupianhou": "空",
"ssbiaotiqian": "空",
"ssbiaotihou": "空",
"sslianjieqian": "空",
"sslianjiehou": "空",
"bfshifouercijiequ": "0",
"bfjiequqian": "空",
"bfjiequhou": "空",
"bfjiequshuzuqian": "id=\"playlist",
"bfjiequshuzuhou": "</ul>",
"zhuangtaiqian": "更新：</span>",
"zhuangtaihou": "</p>",
"daoyanqian": "导演：</span>",
"daoyanhou": "</p>",
"zhuyanqian": "主演：</span>",
"zhuyanhou": "</p>",
"juqingqian": "简介：</span>",
"juqinghou": "</div>",
"bfyshifouercijiequ": "0",
"bfyjiequqian": "空",
"bfyjiequhou": "空",
"bfyjiequshuzuqian": "<a",
"bfyjiequshuzuhou": "/a>",
"bfbiaotiqian": ">",
"bfbiaotihou": "<",
"bflianjieqian": "href=\"",
"bflianjiehou": "\""},
{"name": "神马",
"tihuan": "cnzz.com",
"url": "https://www.smtv8.com",
"fenlei": "喜剧片$/xijupian/index_#动作片$/dongzuopian/index_#科幻片$/kehuanpian/index_#恐怖片$/kongbupian/index_#爱情片$/aiqingpian/index_#战争片$/zhanzhengpian/index_#犯罪片$/fanzuipian/index_#剧情片$/juqingpian/index_#记录片$/jilupian/index_#经典片$/jingdianpian/index_#微拍福利$/weipaifuli/index_#国产剧$/guocanju/index_#香港剧$/xianggangju/index_#台湾剧$/taiwanju/index_#韩国剧$/hanguoju/index_#日本剧$/ribenju/index_#欧美剧$/oumeiju/index_#海外剧$/haiwaiju/index_#综艺$/fun/index_#动漫$/cartoon/index_",
"houzhui": "_______.html",
"shifouercijiequ": "0",
"jiequqian": "空",
"jiequhou": "空",
"jiequshuzuqian": "class=\"link-hover\"",
"jiequshuzuhou": "</a>",
"tupianqian": "src=\"",
"tupianhou": "\"",
"biaotiqian": "title=\"",
"biaotihou": "\"",
"lianjieqian": "href=\"",
"lianjiehou": "\"",
"sousuoqian": "/index.php/ajax/suggest?mid=1&wd=",
"sousuohou": "&limit=500",
"sousuohouzhui": "/kan/",
"ssmoshi": "0",
"sousuoshifouercijiequ": "0",
"jspic": "pic",
"jsname": "name",
"jsid": "id",
"ssjiequqian": "空",
"ssjiequhou": "空",
"ssjiequshuzuqian": "空",
"ssjiequshuzuhou": "空",
"sstupianqian": "空",
"sstupianhou": "空",
"ssbiaotiqian": "空",
"ssbiaotihou": "空",
"sslianjieqian": "空",
"sslianjiehou": "空",
"bfshifouercijiequ": "0",
"bfjiequqian": "空",
"bfjiequhou": "空",
"bfjiequshuzuqian": "class=\"urlli clearfix\"",
"bfjiequshuzuhou": "</div>",
"zhuangtaiqian": "class=\"bz\">",
"zhuangtaihou": "</if>",
"daoyanqian": "导演：</span>",
"daoyanhou": "</a>",
"zhuyanqian": "主演：</span>",
"zhuyanhou": "</a>",
"juqingqian": "剧情：</span>",
"juqinghou": "</div>",
"bfyshifouercijiequ": "0",
"bfyjiequqian": "空",
"bfyjiequhou": "空",
"bfyjiequshuzuqian": "<a",
"bfyjiequshuzuhou": "/a>",
"bfbiaotiqian": ">",
"bfbiaotihou": "<",
"bflianjieqian": "href='",
"bflianjiehou": "'"},
{"name": "奈落",
"url": "https://newfii.com",
"tihuan": "cnzz.com",
"User": "空",
"fenlei": "电影片库$/index.php/vod/show/id/1/page/#剧集片库$/index.php/vod/show/id/2/page/#动漫片库$/index.php/vod/show/id/3/page/#综艺片库$/index.php/vod/show/id/4/page/#B站片库$/index.php/vod/show/id/34/page/#记录片库$/index.php/vod/show/id/27/page/#4K专区片库$/index.php/vod/show/id/33/page/",
"houzhui": ".html",
"shifouercijiequ": "0",
"jiequqian": "空",
"jiequhou": "空",
"jiequshuzuqian": "class=\"module-item-pic\"",
"jiequshuzuhou": "</div>",
"tupianqian": "data-src=\"",
"tupianhou": "\"",
"biaotiqian": "title=\"",
"biaotihou": "\"",
"lianjieqian": "href=\"",
"lianjiehou": "\"",
"sousuoqian": "/index.php/ajax/suggest?mid=1&wd=",
"sousuohou": "&limit=500",
"sousuohouzhui": "/index.php/vod/detail/id/",
"ssmoshi": "0",
"sousuoshifouercijiequ": "0",
"jspic": "pic",
"jsname": "name",
"jsid": "id",
"ssjiequqian": "空",
"ssjiequhou": "空",
"ssjiequshuzuqian": "空",
"ssjiequshuzuhou": "空",
"sstupianqian": "空",
"sstupianhou": "空",
"ssbiaotiqian": "空",
"ssbiaotihou": "空",
"sslianjieqian": "空",
"sslianjiehou": "空",
"bfshifouercijiequ": "0",
"bfjiequqian": "空",
"bfjiequhou": "空",
"bfjiequshuzuqian": "id=\"sort-item",
"bfjiequshuzuhou": "</div>",
"zhuangtaiqian": "集数：</span>",
"zhuangtaihou": "</div>",
"daoyanqian": "导演：</span>",
"daoyanhou": "</div>",
"zhuyanqian": "主演：</span>",
"zhuyanhou": "</div>",
"juqingqian": "剧情：</span>",
"juqinghou": "</div>",
"bfyshifouercijiequ": "0",
"bfyjiequqian": "空",
"bfyjiequhou": "空",
"bfyjiequshuzuqian": "<a",
"bfyjiequshuzuhou": "/a>",
"bfbiaotiqian": "<span>",
"bfbiaotihou": "<",
"bflianjieqian": "href=\"",
"bflianjiehou": "\""},
{"name": "炫猫",
"url": "https://www.xuanmao520.com/",
"tihuan": "cnzz.com",
"user":"空",
"fenlei": "电影$/index.php/vod/type/id/1/#剧集$/index.php/vod/type/id/2/#综艺$/index.php/vod/type/id/3/#动漫$/index.php/vod/type/id/4/",
"houzhui": ".html",
"shifouercijiequ": "0",
"jiequqian": "空",
"jiequhou": "空",
"jiequshuzuqian": "class=\"myui-vodlist__box\"",
"jiequshuzuhou": "</div>",
"tupianqian": "data-original=\"",
"tupianhou": "\"",
"biaotiqian": "title=\"",
"biaotihou": "\"",
"lianjieqian": "href=\"",
"lianjiehou": "\"",
"sousuoqian": "/index.php/ajax/suggest?mid=1&wd=",
"sousuohou": "&limit=500",
"sousuohouzhui": "/index.php/vod/play/id/",
"ssmoshi": "0",
"sousuoshifouercijiequ": "0",
"jspic": "pic",
"jsname": "name",
"jsid": "id",
"ssjiequqian": "空",
"ssjiequhou": "空",
"ssjiequshuzuqian": "空",
"ssjiequshuzuhou": "空",
"sstupianqian": "空",
"sstupianhou": "空",
"ssbiaotiqian": "空",
"ssbiaotihou": "空",
"sslianjieqian": "空",
"sslianjiehou": "空",
"bfshifouercijiequ": "0",
"bfjiequqian": "空",
"bfjiequhou": "空",
"bfjiequshuzuqian": "class=\"myui-content__list scrollbar sort-list clearfix",
"bfjiequshuzuhou": "</ul>",
"zhuangtaiqian": "备注：</div>",
"zhuangtaihou": "</div>",
"daoyanqian": "导演：</span>",
"daoyanhou": "</div>",
"zhuyanqian": "主演：</span>",
"zhuyanhou": "</div>",
"juqingqian": "class=\"span\">",
"juqinghou": "</div>",
"bfyshifouercijiequ": "0",
"bfyjiequqian": "空",
"bfyjiequhou": "空",
"bfyjiequshuzuqian": "<a",
"bfyjiequshuzuhou": "/a>",
"bfbiaotiqian": ">",
"bfbiaotihou": "<",
"bflianjieqian": "href=\"",
"bflianjiehou": "\""},
 { "name": "尘落",
 "url": "https://v.xuangz.cn/",
 "tihuan": "cnzz.com",
 "User": "空",
 "fenlei": "电视剧$/whole/2_______0_addtime_#电影$/whole/1_______0_addtime_#综艺$/whole/4_______0_addtime_#动漫$/whole/3_______0_addtime_#国产剧$/whole/2__国产剧_____0_addtime_#日韩剧$//whole/2__日韩剧_____0_addtime_#欧美剧$/whole/2__欧美剧_____0_addtime_#动作片$/whole/1__动作片_____0_addtime_",
 "houzhui": ".html",
 "shifouercijiequ": "0",
 "jiequqian": "空",
 "jiequhou": "空",
 "jiequshuzuqian": "class=\"movie-item-in",
 "jiequshuzuhou": "</div>",
 "tupianqian": "src=\"",
 "tupianhou": "\"",
 "biaotiqian": "title=\"",
 "biaotihou": "\"",
 "lianjieqian": "href=\"",
 "lianjiehou": "\"",
 "sousuoqian": "/?c=search&wd=",
 "sousuohou": "&limit=500",
 "sousuohouzhui": "/show/",
 "ssmoshi": "1",
 "sousuoshifouercijiequ": "0",
 "jspic": "pic",
 "jsname": "name",
 "jsid": "id",
 "ssjiequqian": "空",
 "ssjiequhou": "空",
 "ssjiequshuzuqian": "class=\"movie-item-in\"",
 "ssjiequshuzuhou": "</div>",
 "sstupianqian": "src=\"",
 "sstupianhou": "\"",
 "ssbiaotiqian": "title=\"",
 "ssbiaotihou": "\"",
 "sslianjieqian": "href=\"",
 "sslianjiehou": "\"",
 "bfshifouercijiequ": "0",
 "bfjiequqian": "空",
 "bfjiequhou": "空",
 "bfjiequshuzuqian": "id=\"tvTabContent",
 "bfjiequshuzuhou": "</ul>",
 "zhuangtaiqian": "年份",
 "zhuangtaihou": "</a>",
 "daoyanqian": "导演",
 "daoyanhou": "</a>",
 "zhuyanqian": "主演",
 "zhuyanhou": "</a>",
 "juqingqian": "<br>",
 "juqinghou": "</span>",
 "bfyshifouercijiequ": "0",
 "bfyjiequqian": "空",
 "bfyjiequhou": "空",
 "bfyjiequshuzuqian": "<a",
 "bfyjiequshuzuhou": "/a>",
 "bfbiaotiqian": ">",
 "bfbiaotihou": "<",
 "bflianjieqian": "href=\"",
 "bflianjiehou": "\""},
{"name": "剧白白-蓝光",
"url": "https://www.jubaibai.cc",
"tihuan": "cnzz.com",
"User": "空",
"fenlei": "电视剧$/type/dianshiju-#电影$/type/dianying-#综艺$/type/zongyi-#动漫$/type/dongman-#纪录片$/type/jilupian-#动作片$/vodshow/id/dongzuopian/page/#喜剧片$/vodshow/id/xijupian/page/#爱情片$/vodshow/id/aiqingpian/page/#科幻片$/vodshow/id/kehuanpian/page/#恐怖片$/vodshow/id/kongbupian/page/#剧情片$/vodshow/id/juqingpian/page/#战争片$/vodshow/id/zhanzhengpian/page/#国产剧$/vodshow/id/guochanju/page/#港台剧$/vodshow/id/gangtaiju/page/#日韩剧$/vodshow/id/rihanju/page/#欧M剧$/vodshow/id/oumeiju/page/#其他剧$/vodshow/id/qitaju/page/",
"houzhui": ".html",
"shifouercijiequ": "0",
"jiequqian": "空",
"jiequhou": "空",
"jiequshuzuqian": "class=\"stui-vodlist__box\"",
"jiequshuzuhou": "</a>",
"tupianqian": "original=\"",
"tupianhou": "\"",
"biaotiqian": "title=\"",
"biaotihou": "\"",
"lianjieqian": "href=\"",
"lianjiehou": "\"",
"sousuoqian": "/index.php/ajax/suggest?mid=1&wd=",
"sousuohou": "&limit=500",
"sousuohouzhui": "/vod/",
"ssmoshi": "0",
"sousuoshifouercijiequ": "0",
"jspic": "pic",
"jsname": "name",
"jsid": "id",
"ssjiequqian": "空",
"ssjiequhou": "空",
"ssjiequshuzuqian": "空",
"ssjiequshuzuhou": "空",
"sstupianqian": "空",
"sstupianhou": "空",
"ssbiaotiqian": "空",
"ssbiaotihou": "空",
"sslianjieqian": "空",
"sslianjiehou": "空",
"bfshifouercijiequ": "0",
"bfjiequqian": "空",
"bfjiequhou": "空",
"bfjiequshuzuqian": "class=\"stui-content__playlist sort-list",
"bfjiequshuzuhou": "</ul>",
"zhuangtaiqian": "class=\"data hidden-xs\">类型：",
"zhuangtaihou": "</p>",
"daoyanqian": "class=\"data\">导演：",
"daoyanhou": "</p>",
"zhuyanqian": "class=\"data\">主演：",
"zhuyanhou": "</p>",
"juqingqian": "style=\"display: none;\">",
"juqinghou": "</span>",
"bfyshifouercijiequ": "0",
"bfyjiequqian": "空",
"bfyjiequhou": "空",
"bfyjiequshuzuqian": "<a",
"bfyjiequshuzuhou": "/a>",
"bfbiaotiqian": ">",
"bfbiaotihou": "<",
"bflianjieqian": "href=\"",
"bflianjiehou": "\""},
{"name": "天空资源",
"url": "https://www.tkys.tv",
"tihuan": "cnzz.com",
"fenlei": "电影$/vodtype/1-#综艺$/vodtype/3-#动漫$/vodtype/4-#国产剧$/vodshow/area/内地/id/2/page/#港剧$/vodshow/area/香港/id/2/page/#韩剧$/vodshow/area/韩国/id/2/page/#M剧$/vodshow/area/M国/id/2/page/#泰剧$/vodshow/area/泰国/id/2/page/#日剧$/vodshow/area/日本/id/2/page/#台剧$/vodshow/area/台湾/id/2/page/#英剧$/vodshow/area/英国/id/2/page/",
"houzhui": ".html",
"shifouercijiequ": "0",
"jiequqian": "空",
"jiequhou": "空",
"jiequshuzuqian": "class=\"col-lg-8",
"jiequshuzuhou": "</span>",
"tupianqian": "original=\"",
"tupianhou": "\"",
"biaotiqian": "title=\"",
"biaotihou": "\"",
"lianjieqian": "href=\"",
"lianjiehou": "\"",
"sousuoqian": "/index.php/ajax/suggest?mid=1&wd=",
"sousuohou": "&limit=500",
"sousuohouzhui": "/voddetail/",
"ssmoshi": "0",
"sousuoshifouercijiequ": "0",
"jspic": "pic",
"jsname": "name",
"jsid": "id",
"ssjiequqian": "空",
"ssjiequhou": "空",
"ssjiequshuzuqian": "空",
"ssjiequshuzuhou": "空",
"sstupianqian": "空",
"sstupianhou": "空",
"ssbiaotiqian": "空",
"ssbiaotihou": "空",
"sslianjieqian": "空",
"sslianjiehou": "空",
"bfshifouercijiequ": "0",
"bfjiequqian": "空",
"bfjiequhou": "空",
"bfjiequshuzuqian": "id=\"playlist",
"bfjiequshuzuhou": "</ul>",
"zhuangtaiqian": "备注：</span>",
"zhuangtaihou": "</div>",
"daoyanqian": "导演：</span>",
"daoyanhou": "</div>",
"zhuyanqian": "主演：</span>",
"zhuyanhou": "</div>",
"juqingqian": "class=\"video-info-item video-info-content vod_content\">",
"juqinghou": "</span>",
"bfyshifouercijiequ": "0",
"bfyjiequqian": "空",
"bfyjiequhou": "空",
"bfyjiequshuzuqian": "<a",
"bfyjiequshuzuhou": "/a>",
"bfbiaotiqian": ">",
"bfbiaotihou": "<",
"bflianjieqian": "href=\"",
"bflianjiehou": "\""},
{"name": "饭团资源",
"url": "https://fantuan.tv",
"tihuan": "cnzz.com",
"User": "User-Agent:Dart/2.14 (dart:io)",
"fenlei": "电视剧$/vodtype/2-#电影$/vodtype/1-#综艺$/vodtype/3-#韩国综艺$/vodtype/31-#动漫$/vodtype/4-#国产剧$/vodtype/13-#港剧$/vodtype/14-#韩剧$/vodtype/15-#M剧$/vodtype/16-#日剧$/vodtype/24-#泰剧$/vodtype/25-#台剧$/vodtype/26-#英剧$/vodtype/27-#其他剧$/vodtype/28-",
"houzhui": ".html",
"shifouercijiequ": "1",
"jiequqian": "class=\"myui-vodlist clearfix",
"jiequhou": "</ul>",
"jiequshuzuqian": "class=\"myui-vodlist__thumb",
"jiequshuzuhou": "</span>",
"tupianqian": "original=\"",
"tupianhou": "\"",
"biaotiqian": "title=\"",
"biaotihou": "\"",
"lianjieqian": "href=\"",
"lianjiehou": "\"",
"sousuoqian": "/index.php/ajax/suggest?mid=1&wd=",
"sousuohou": "&limit=50",
"sousuohouzhui": "/voddetail/",
"ssmoshi": "0",
"sousuoshifouercijiequ": "0",
"jspic": "pic",
"jsname": "name",
"jsid": "id",
"ssjiequqian": "空",
"ssjiequhou": "空",
"ssjiequshuzuqian": "空",
"ssjiequshuzuhou": "空",
"sstupianqian": "空",
"sstupianhou": "空",
"ssbiaotiqian": "空",
"ssbiaotihou": "空",
"sslianjieqian": "空",
"sslianjiehou": "空",
"bfshifouercijiequ": "0",
"bfjiequqian": "空",
"bfjiequhou": "空",
"bfjiequshuzuqian": "class=\"myui-content__list",
"bfjiequshuzuhou": "</ul>",
"zhuangtaiqian": "更新：</span>",
"zhuangtaihou": "</p>",
"daoyanqian": "导演：</span>",
"daoyanhou": "</p>",
"zhuyanqian": "主演：</span>",
"zhuyanhou": "</p>",
"juqingqian": "class=\"data\" style=\"display: none;\">",
"juqinghou": "</span>",
"bfyshifouercijiequ": "0",
"bfyjiequqian": "空",
"bfyjiequhou": "空",
"bfyjiequshuzuqian": "<a",
"bfyjiequshuzuhou": "/a>",
"bfbiaotiqian": ">",
"bfbiaotihou": "<",
"bflianjieqian": "href=\"",
"bflianjiehou": "\""},
{"name": "资源工厂",
"url": "http://www.ysgc.cc",
"User": "空",
"fenlei": "电视剧$/vodshow/2--------#电影$/vodshow/1--------#综艺$/vodshow/3--------#动漫$/vodshow/4--------#番剧$/vodshow/26--------#国产剧$/vodshow/13--------#港台剧$/vodshow/14--------#日韩剧$/vodshow/15--------#欧M剧$/vodshow/16--------#动作片$/vodshow/1---动作-----#喜剧片$/vodshow/1---喜剧-----#爱情片$/vodshow/1---爱情-----#科幻片$/vodshow/1---科幻-----#恐怖片$/vodshow/1---恐怖-----#剧情片$/vodshow/1---剧情-----#战争片$/vodshow/1---战争-----#武侠片$/vodshow/1---武侠-----",
"houzhui": "---.html",
"shifouercijiequ": "0",
"jiequqian": "空",
"jiequhou": "空",
"jiequshuzuqian": "class=\"myui-vodlist__box\"",
"jiequshuzuhou": "</span>",
"tupianqian": "original=\"",
"tupianhou": "\"",
"biaotiqian": "title=\"",
"biaotihou": "\"",
"lianjieqian": "href=\"",
"lianjiehou": "\"",
"sousuoqian": "/index.php/ajax/suggest?mid=1&wd=",
"sousuohou": "&limit=500",
"sousuohouzhui": "/voddetail/",
"ssmoshi": "0",
"sousuoshifouercijiequ": "0",
"jspic": "pic",
"jsname": "name",
"jsid": "id",
"ssjiequqian": "空",
"ssjiequhou": "空",
"ssjiequshuzuqian": "空",
"ssjiequshuzuhou": "空",
"sstupianqian": "空",
"sstupianhou": "空",
"ssbiaotiqian": "空",
"ssbiaotihou": "空",
"sslianjieqian": "空",
"sslianjiehou": "空",
"bfshifouercijiequ": "0",
"bfjiequqian": "空",
"bfjiequhou": "空",
"bfjiequshuzuqian": "id=\"playlist",
"bfjiequshuzuhou": "</ul>",
"zhuangtaiqian": "class=\"otherbox\">",
"zhuangtaihou": "</p>",
"daoyanqian": "导演：</span>",
"daoyanhou": "</p>",
"zhuyanqian": "主演：</span>",
"zhuyanhou": "</p>",
"juqingqian": "<span class=\"data\"",
"juqinghou": "</span>",
"bfyshifouercijiequ": "0",
"bfyjiequqian": "空",
"bfyjiequhou": "空",
"bfyjiequshuzuqian": "<a",
"bfyjiequshuzuhou": "/a>",
"bfbiaotiqian": ">",
"bfbiaotihou": "<",
"bflianjieqian": "href=\"",
"bflianjiehou": "\""},
{"name": "火火资源",
"url": "https://www.huohuo99.com",
"tihuan": "",
"User": "空",
"fenlei":"动作片$/vodtype/6-#喜剧片$/vodtype/7-#爱情片$/vodtype/8-#科幻片$/vodtype/9-#恐怖片$/vodtype/10-#剧情片$/vodtype/11-#战争片$/vodtype/12-#惊悚片$/vodtype20-#悬疑片$vodtype/23-#动画片$/vodtype/24-#国产剧$/vodtype/13-#港台剧$/vodtype/14-#日韩剧$/vodtype15-#欧M剧$vodtype/16-#番剧$/vodtype/31-#综艺$/vodtype/4-#记录片$/vodtype/5-",
"houzhui": ".html",
"shifouercijiequ": "0",
"jiequqian": "空",
"jiequhou": "空",
"jiequshuzuqian": "class=\"hl-list-item hl",
"jiequshuzuhou": "</div>",
"tupianqian": "data-original=\"",
"tupianhou": "\"",
"biaotiqian": "title=\"",
"biaotihou": "\"",
"lianjieqian": "href=\"",
"lianjiehou": "\"",
"sousuoqian":"/index.php/ajax/suggest?mid=1&wd=",
"sousuohou": "&limit=500",
"sousuohouzhui": "/voddetail/",
"ssmoshi": "0",
"sousuoshifouercijiequ": "0",
"jspic": "pic",
"jsname": "name",
"jsid": "id",
"ssjiequqian": "空",
"ssjiequhou": "空",
"ssjiequshuzuqian": "空",
"ssjiequshuzuhou": "空",
"sstupianqian": "空",
"sstupianhou": "空",
"ssbiaotiqian": "空",
"ssbiaotihou": "空",
"sslianjieqian": "空",
"sslianjiehou": "空",
"bfshifouercijiequ": "0",
"bfjiequqian": "空",
"bfjiequhou": "空",
"bfjiequshuzuqian": " id=\"hl-plays-list",
"bfjiequshuzuhou": "</ul>",
"zhuangtaiqian": "状态：</em>",
"zhuangtaihou": "</a>",
"daoyanqian": "导演：</em>",
"daoyanhou": "</a>",
"zhuyanqian": "主演：</em>",
"zhuyanhou": "</a>",
"juqingqian": "简介：</em>",
"juqinghou": "</li>",
"bfyshifouercijiequ": "0",
"bfyjiequqian": "空",
"bfyjiequhou": "空",
"bfyjiequshuzuqian": "<a",
"bfyjiequshuzuhou": "/a>",
"bfbiaotiqian": ">",
"bfbiaotihou": "<",
"bflianjieqian": "href=\"",
"bflianjiehou": "\""},
{"name": "达达龟",
"url": "http://www.dadagui.com",
"tihuan": "cnzz.com",
"User": "空",
"fenlei": "电视剧$/vodtype/2-#电影$/vodtype/1-#综艺$/vodtype/3-#动漫$/vodtype/4-",
"houzhui": ".html",
"shifouercijiequ": "0",
"jiequqian": "空",
"jiequhou": "空",
"jiequshuzuqian": "class=\"stui-vodlist__box",
"jiequshuzuhou": "</li>",
"tupianqian": "data-original=\"",
"tupianhou": "\"",
"biaotiqian": "title=\"",
"biaotihou": "\"",
"lianjieqian": "href=\"",
"lianjiehou": "\"",
"sousuoqian": "/vodsearch/-------------.html?wd=",
"sousuohou": "",
"sousuohouzhui": "/voddetail/",
"ssmoshi": "1",
"sousuoshifouercijiequ": "0",
"jspic": "空",
"jsname": "空",
"jsid": "空",
"ssjiequqian": "空",
"ssjiequhou": "空",
"ssjiequshuzuqian": "class=\"thumb",
"ssjiequshuzuhou": "</li>",
"sstupianqian": "data-original=\"",
"sstupianhou": "\"",
"ssbiaotiqian": "title=\"",
"ssbiaotihou": "\"",
"sslianjieqian": "href=\"",
"sslianjiehou": "\"",
"bfshifouercijiequ": "0",
"bfjiequqian": "空",
"bfjiequhou": "空",
"bfjiequshuzuqian": "class=\"stui-content__playlist clearfix",
"bfjiequshuzuhou": "</ul>",
"zhuangtaiqian": "类型：",
"zhuangtaihou": "</p>",
"daoyanqian": "导演：",
"daoyanhou": "</p >",
"zhuyanqian": "主演：",
"zhuyanhou": "</p >",
"juqingqian": "style=\"display: none;\">",
"juqinghou": "</span>",
"bfyshifouercijiequ": "0",
"bfyjiequqian": "空","bfyjiequhou": "空",
"bfyjiequshuzuqian": "<a",
"bfyjiequshuzuhou": "/a>",
"bfbiaotiqian": ">",
"bfbiaotihou": "<",
"bflianjieqian": "href=\"",
"bflianjiehou": "\""},
{"name": "黑洞",
"url": "https://www.nulltm.com",
"tihuan": "cnzz.com",
"User": "空",
"fenlei": "电视剧$/vodtype/2-#电影$/vodtype/1-#综艺$/vodtype/3-#动漫$/vodtype/4-",
"houzhui": ".html",
"shifouercijiequ": "0",
"jiequqian": "空",
"jiequhou": "空",
"jiequshuzuqian": "class=\"stui-vodlist__box",
"jiequshuzuhou": "</li>",
"tupianqian": "data-original=\"",
"tupianhou": "\"",
"biaotiqian": "title=\"",
"biaotihou": "\"",
"lianjieqian": "href=\"",
"lianjiehou": "\"",
"sousuoqian": "/vodsearch/",
"sousuohou": "----------1---.html",
"sousuohouzhui": "/voddetail/",
"ssmoshi": "1",
"sousuoshifouercijiequ": "0",
"jspic": "空",
"jsname": "空",
"jsid": "空",
"ssjiequqian": "空",
"ssjiequhou": "空",
"ssjiequshuzuqian": "class=\"stui-vodlist__box",
"ssjiequshuzuhou": "</li>",
"sstupianqian": "data-original=\"",
"sstupianhou": "\"",
"ssbiaotiqian": "title=\"",
"ssbiaotihou": "\"",
"sslianjieqian": "href=\"",
"sslianjiehou": "\"",
"bfshifouercijiequ": "0",
"bfjiequqian": "空",
"bfjiequhou": "空",
"bfjiequshuzuqian": "class=\"stui-content__playlist clearfix",
"bfjiequshuzuhou": "</ul>",
"zhuangtaiqian": "更新：",
"zhuangtaihou": "</p>",
"daoyanqian": "导演：",
"daoyanhou": "</p>",
"zhuyanqian": "主演：",
"zhuyanhou": "</p>",
"juqingqian": "简介：",
"juqinghou": "</p>",
"bfyshifouercijiequ": "0",
"bfyjiequqian": "空",
"bfyjiequhou": "空",
"bfyjiequshuzuqian": "<li",
"bfyjiequshuzuhou": "</li>",
"bfbiaotiqian": "\">",
"bfbiaotihou": "</a>",
"bflianjieqian": "href=\"",
"bflianjiehou": "\""}
]
}
